apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: koncepts-prod
  namespace: openshift-gitops
spec:
  destination:
    namespace: koncepts-prod
    server: https://kubernetes.default.svc
  project: default
  source:
    path: overlays/prod
    repoURL: https://github.com/smrowley-lab/argo-kustomize-demo
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true