apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quarkus-subchart
  namespace: openshift-gitops
spec:
  destination:
    namespace: helm-demo
    server: https://kubernetes.default.svc
  project: default
  source:
    path: quarkus-subchart/
    repoURL: https://github.com/smrowley-lab/gitops-root
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
